/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/

library;
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData genderless_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData genderless = IconData(0xf22d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handLizard = IconData(0xf258, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viruses = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}



class CategoryIcons {
  CategoryIcons._();

  static const String _fontFamily = 'CategoryIcons';

  static const IconData sexMove = IconData(0xe900, fontFamily: _fontFamily);
  static const IconData condom = IconData(0xe901, fontFamily: _fontFamily);
  static const IconData uterus = IconData(0xe902, fontFamily: _fontFamily);
  static const IconData two = IconData(0xe903, fontFamily: _fontFamily);
  static const IconData nonbinary = IconData(0xe904, fontFamily: _fontFamily);
}